name: update_dnslink
on:
  release:
    types: [created]

jobs:
  update_dnslink:
    runs-on: ubuntu-latest
    name: Update a DNSLink
    env:
      BUCKET_NAME: 'gatsby-ipfs-blog'
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build Gatsby Site
      uses: jzweifel/gatsby-cli-github-action@master
      with:
        gatsby-arg: build
    - name: Bucket push action
      id: push
      uses: textileio/github-action-bucket-push@master
      with:
        bucket-name: '${{ env.BUCKET_NAME }}'
        path: 'public/*'
        token: ${{ secrets.TEXTILE_AUTH_TOKEN }}
    - name: Update DNSLink
      env:
        CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
        CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        RECORD_DOMAIN: ${{ secrets.DOMAIN_NAME }}
        RECORD_NAME: '_dnslink.${{ secrets.SUBDOMAIN }}'
      id: dnslink
      uses: textileio/cloudflare-update-dnslink@master
      with:
        cid: '${{ steps.push.outputs.cid }}'
